name: language
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  get_it: ^7.1.4
  kt_dart: ^0.9.1
  flutter_bloc: ^7.1.0
  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3
  flutter_secure_storage: ^4.2.1
  dartz: ^0.10.0-nullsafety.2
  aqb_api:
    path: ../aqb_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.4
  build_runner: ^2.0.5
  json_serializable: ^5.0.0
  lint: ^1.5.3

flutter:
