name: resource
description: A new flutter plugin project.
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  dio: ^4.0.0
  get_it: ^7.1.4
  kt_dart: ^0.9.1
  flutter_bloc: ^7.3.0
  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3
  dartz: ^0.10.0-nullsafety.2
  aqb_api:
    path: ../aqb_api
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.4
  json_serializable: ^5.0.0
  lint: ^1.5.3
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  mocktail: ^0.1.4

dependency_overrides:
  analyzer: ^2.2.0
  test: ^1.17.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.aqbooking.resource
        pluginClass: ResourcePlugin
      ios:
        pluginClass: ResourcePlugin
