name: config
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  dio: ^4.0.0
  get_it: ^7.1.4
  kt_dart: ^0.9.1
  flutter_bloc: ^8.0.0
  json_annotation: ^4.1.0
  freezed_annotation: ^0.14.3
  dartz: ^0.10.0-nullsafety.2
  rxdart: ^0.27.2
  pretty_dio_logger: ^1.1.1
  aqb_api:
    path: ../aqb_api
  smart_select:
    git:
      url: "https://github.com/vitcon-lonton/flutter_smart_select"
      ref: null-safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^0.14.4
  json_serializable: ^5.0.0
  lint: ^1.5.3
  hive_generator: ^1.1.0
  build_runner: ^2.1.1
  mocktail: ^0.1.4

dependency_overrides:
  test: ^1.17.12
  analyzer: ^2.2.0
  flutter_lints: ^1.0.0

flutter:
